### ISSUE TITLE
Activation code is easy to brute-force 

### ISSUE THREAD

**Issue by barbushin** [dnegometyanov/cordial-auth#1]
https://github.com/dnegometyanov/cordial-auth/blob/9ecd59edfbb3597e1d1261c3d9e829d52a5eae40/app/Services/AuthService.php#L34

**Comment by dnegometyanov** [comment]
Agree, my error to not treat this task as production-ready solution and not keeping enough attention to security.

**Comment by dnegometyanov** [comment]
Have resolved issue in recent commits.
