### ISSUE TITLE
Data validation must be encapsulated in AuthService class 

### ISSUE THREAD

**Issue by barbushin** [dnegometyanov/cordial-auth#3]
https://github.com/dnegometyanov/cordial-auth/blob/9ecd59edfbb3597e1d1261c3d9e829d52a5eae40/app/Http/Controllers/AuthController.php#L74

Otherwise if we call AuthService from another API provider (not REST), there will be no validation.

**Comment by dnegometyanov** [comment]
Okay, good point, probably we should leave request validation outside of AuthService, but agree that to validate parameters passed to AuthService is a good idea.

**Comment by dnegometyanov** [comment]
Have resolved issue in recent commits.
