### ISSUE TITLE
Request object should be passed in controller methods (not in constructor)

### ISSUE THREAD

**Issue by barbushin** [dnegometyanov/cordial-auth#4]
https://github.com/dnegometyanov/cordial-auth/blob/9ecd59edfbb3597e1d1261c3d9e829d52a5eae40/app/Http/Controllers/AuthController.php#L31

**Comment by dnegometyanov** [comment]
Agree, I thought even of creating custom form requests classes and passing them for each action instead of validating request data inside actions. (https://laravel.com/docs/5.8/validation#form-request-validation)

**Comment by dnegometyanov** [comment]
Have resolved issue in recent commits.
