### ISSUE TITLE
Password hash function

### ISSUE THREAD

**Issue by barbushin** [dnegometyanov/cordial-auth#8]
https://github.com/dnegometyanov/cordial-auth/blob/9ecd59edfbb3597e1d1261c3d9e829d52a5eae40/app/Services/AuthService.php#L31

If we use Hash::check(), why not use Hash::make() to generate it?

**Comment by dnegometyanov** [comment]
Agree, this one was fixed here https://github.com/dnegometyanov/cordial-auth/commit/92effc5798e06f9e4b305b4b8209e60ea06168e0

**Comment by barbushin** [comment]
@dnegometyanov Ok, but there is no need to fix. Please keep source code as it was before code review, so we can keep discussing your original solutions.

**Comment by dnegometyanov** [comment]
yeah, this one was fixed before I got the review.

**Comment by dnegometyanov** [comment]
Have resolved issue in recent commits.
