### ISSUE TITLE
Easy to brute-force password change method

### ISSUE THREAD

**Issue by barbushin** [dnegometyanov/cordial-auth#9]
https://github.com/dnegometyanov/cordial-auth/blob/9ecd59edfbb3597e1d1261c3d9e829d52a5eae40/app/Services/AuthService.php#L112

All we need to know is user's email, and then send 900k requests to find correct reset code. With 2k rps it will take less than 10 min.

**Comment by dnegometyanov** [comment]
Agree, my error to not treat this task as production-ready solution and not keeping enough attention to security.

**Comment by dnegometyanov** [comment]
Have resolved issue in recent commits.
